UCMRS/UCMRS/Controllers/ProviderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UCMRS.Models.DB;
using UCMRS.Models.UnivContext;

namespace UCMRS.Controllers
{
    public class ProviderController : Controller
    {
        private UniContext db = new UniContext(); 

        // GET: Provider
        public ActionResult Index()
        {
            return View();
        }

        #region Semester

        public ActionResult SemesterIndex()
        {
            try
            {
                var semesters = db.Semesters.ToList();
                if (semesters != null)
                {
                    return View(semesters);
                }
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                throw;
            }
            return RedirectToAction("");
        }

        /// <summary>
        /// Load input form for Semester
        /// </summary>
        /// <returns></returns>
        public ActionResult SaveSemester()
        {
            try
            {
                return View();
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
                throw;
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SaveSemester(Semester semester)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Semesters.Add(semester);
                    db.SaveChanges();
                    return RedirectToAction("SemesterIndex");
                }
                return RedirectToAction("SaveSemester");
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
                throw;
            }
        }
        #endregion

        #region Designation

        [HttpGet]
        public ActionResult IndexDesignation()
        {
            try
            {
                var designation = db.Designations.ToList();
                if (designation.Any())
                {
                    return View(designation);
                }
                return View();
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                throw;
            }
        }

        /// <summary>
        /// Load input form for Semester
        /// </summary>
        /// <returns></returns>
        public ActionResult SaveDesignation()
        {
            try
            {
                return View();
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
                throw;
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SaveDesignation(Designation designation)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Designations.Add(designation);
                    db.SaveChanges();
                    return RedirectToAction("IndexDesignation");
                }
                return RedirectToAction("SaveSemester");
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
                throw;
            }
        }

        #endregion

        #region Rooms

        public ActionResult IndexRoom()
        {
            try
            {
                var rooms = db.Rooms.ToList();
                if (rooms.Any())
                {
                    return View(rooms);
                }
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                throw;
            }
            return RedirectToAction("");
        }

        /// <summary>
        /// Load input form for Semester
        /// </summary>
        /// <returns></returns>
        public ActionResult SaveRoom()
        {
            try
            {
                return View();
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
                throw;
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SaveRoom(Room room)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Rooms.Add(room);
                    db.SaveChanges();
                    return RedirectToAction("IndexRoom");
                }
                return RedirectToAction("SaveRoom");
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
                throw;
            }
        }

        #endregion
    }
}

UCMRS/UCMRS/Views/Provider/IndexDesignation.cshtml
@model IEnumerable<UCMRS.Models.DB.Designation>

@{
    ViewBag.Title = "IndexDesignation";
}
@Html.ActionLink("Create New", "SaveDesignation", "Provider")
<div class="card">
    <div class="card-header">Designations</div>
    <div class="card-body">
        <table class="table table-bordered table-striped">
            <tr>
                <th>SL</th>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th></th>
            </tr>

            @{
                int a = 0;
                foreach (var item in Model)
                {
                    a = a + 1;
                    <tr>
                        <td>@a</td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td></td>
                        @*<td>
                                @Html.ActionLink("Edit", "Edit", new {id = item.Id}) |
                                @Html.ActionLink("Details", "Details", new {id = item.Id}) |
                                @Html.ActionLink("Delete", "Delete", new {id = item.Id})
                            </td>*@
                    </tr>
                }
            }

        </table>
    </div>
</div>

UCMRS/UCMRS/Views/Provider/IndexRoom.cshtml
@model IEnumerable<UCMRS.Models.DB.Room>

@{
    ViewBag.Title = "IndexRoom";
}

<div class="card text-center">
    <h3 class="card-header">Rooms</h3>
    <div class="card-body">
        <div class="offset-4 col-md-4">
            <table class="table table-striped table-bordered">
                @{
                    var sl = 0;
                    <tr>
                        <th style="text-align: center">SL#</th>
                        <th style="text-align: center">
                            @Html.DisplayNameFor(model => model.Name)
                        </th>
                        <th style="text-align: center">
                            @Html.DisplayNameFor(model => model.RoomNo)
                        </th>
                        @*<th></th>*@
                    </tr>

                    foreach (var item in Model)
                    {
                        sl = sl + 1;
                        <tr>
                            <td style="text-align: right; width: 2%">@sl</td>
                            <td style="text-align: left; width: 15%">
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>
                            <td style="text-align: right; width: 15%">
                                @Html.DisplayFor(modelItem => item.RoomNo)
                            </td>
                            @*<td>
                        @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
                        @Html.ActionLink("Details", "Details", new { id=item.Id }) |
                        @Html.ActionLink("Delete", "Delete", new { id=item.Id })
                    </td>*@
                        </tr>
                    }
                }

            </table>
        </div>
    </div>
</div>

UCMRS/UCMRS/Views/Provider/SaveDesignation.cshtml
@model UCMRS.Models.DB.Designation

@{
    ViewBag.Title = "SaveDesignation";
}

@using (Html.BeginForm("SaveDesignation", "Provider", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="card col-4">
        <div class="card-header">Designation</div>
        <div class="card-body">
            <div class="row">
                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "col-form-label " })
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="row">
                <div class="form-group">
                    <div class="offset-11 col-md-12">
                        <input type="submit" value="Create" class="btn btn-default" />
                    </div>
                </div>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

UCMRS/UCMRS/Views/Provider/SaveRoom.cshtml
@model UCMRS.Models.DB.Room

@{
    ViewBag.Title = "SaveRoom";
}


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })


    <div class="card text-center">
        <h3 class="card-header">Room</h3>
        <hr />
        <div class="card-body">
            <div class="row form-group">
                <div class="col-md-5">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-md-5">
                    @Html.LabelFor(model => model.RoomNo, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.RoomNo, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.RoomNo, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Create" class="btn btn-default" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
        
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

UCMRS/UCMRS/Views/Provider/SaveSemester.cshtml
@model UCMRS.Models.DB.Semester

@{
    ViewBag.Title = "SaveSemester";
}

@using (Html.BeginForm("SaveSemester","Provider",FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
   
    <div class="card">
        <div class="card-header">
            Semester Information
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "col-form-label" })
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="offset-md-5 col-md-6">
                    <div class="form-group">
                        <input type="submit" value="Save" class="btn" />
                    </div>
                </div>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

UCMRS/UCMRS/Views/Provider/SemesterIndex.cshtml
@model IEnumerable<UCMRS.Models.DB.Semester>

@{
    ViewBag.Title = "SemesterIndex";
}

@Html.ActionLink("Add Semester", "SaveSemester", "Provider")

<div class="card">
    <div class="card-header">
        Semesters
    </div>
    <div class="card-body">
        <table class="table table-bordered">
            <tr>
                <th>SL#</th>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th></th>
            </tr>
            @{ var a = 0;}
            @foreach (var item in Model)
            {
                a = a + 1;
                <tr>
                    <td>@a</td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.ActionLink(" ", "Edit", "Provider", new { id = item.Id }, new { @class = "btn btn-success btn-sm fa fa-pencil-square-o" })&nbsp;
                        @Html.ActionLink(" ", "Delete", "Provider", new { id = item.Id }, new { @class = "btn btn-danger btn-sm fa fa-trash" })
                    </td>
                </tr>
            }

        </table>
    </div>
</div>