UCMRS/UCMRS/Controllers/HelperController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using UCMRS.Models.UnivContext;

namespace UCMRS.Controllers
{
    public class HelperController : Controller
    {
        UniContext db = new UniContext();
        // GET: Helper


            // Generate Registration No--------------
        public JsonResult GenerateRegNo(int id)
        {
            string regNo;
            var deptCode = db.Departments.Where(d => d.Id == id).Select(s => s.Code).SingleOrDefault();
            int codeCount = db.Students.Count(d => d.DeptId == id)+1;
            int year = DateTime.Now.Year;
            string date = db.Students.Where(d => d.DeptId == id).Select(y => y.Date).FirstOrDefault().ToShortDateString();
            //string year = dt.Substring(4,4);

            if (codeCount < 10)
            {
                regNo = deptCode +"-"+ year +"-00" + codeCount;
            }
            else if (codeCount < 100)
            {
                regNo = deptCode + "0" + codeCount;
            }
            else 
            {
                regNo = deptCode + " " +codeCount;
            }

            return Json(regNo, JsonRequestBehavior.AllowGet);
        }


        //------------ Load Name, Email, Department upon Selecting Registration No---- 

        public JsonResult RegDropDown(int id)
        {
            var studentInfo = (from st in db.Students
                join d in db.Departments on st.DeptId equals d.Id
                where st.Id == id
                select new
                {
                    Name = st.Name,
                    Email = st.Email,
                    DeptName = d.Name
                }).FirstOrDefault();
            return Json(studentInfo, JsonRequestBehavior.AllowGet);
        }


        //---------Dropdown for Course Statistics---------------

        //public JsonResult CourseStat(int id)
        //{
        //    var cStat = (from cstat in db.CourseAssigns
        //        join t in db.Teachers on cstat.TeacherId equals t.Id
        //        join c in db.Courses on cstat.CourseId equals c.Id
        //        join s in db.Semesters on c.SemId equals s.Id
        //        where t.DeptId == id
        //        select new
        //        {
        //            code = c.Code,
        //            name = c.Name,
        //            sem = s.Name,  //(from s in db.Semesters where c.SemId == s.Id select new { s.Name }),
        //            assignTo = t.Name
        //        }).ToList();

        //    return Json(cStat, JsonRequestBehavior.AllowGet);
        //}
    }
}

UCMRS/UCMRS/Controllers/UCRMSController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using UCMRS.Models;
using UCMRS.Models.Entity;
using UCMRS.Models.UnivContext;
using UCMRS.Models.View;

namespace UCMRS.Controllers
{
    public class UCRMSController : Controller
    {
        private UniContext db = new UniContext();
        private DropDownData d = new DropDownData();

        #region Department Settings...

        // GET: UCRMS
        public ActionResult Index()
        {
            try
            {
                return View(db.Departments.ToList());
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                throw;
            }
        }

        // GET: UCRMS/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Department department = db.Departments.Find(id);
            if (department == null)
            {
                return HttpNotFound();
            }
            return View(department);
        }

        // GET: UCRMS/Create
        public ActionResult AddDepartment()
        {
            return View();
        }

        // POST: UCRMS/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddDepartment([Bind(Include = "Id,Code,Name")] Department department)
        {
            if (ModelState.IsValid)
            {
                if (!db.Departments.Any(d => d.Code == department.Code))
                {
                    db.Departments.Add(department);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                {
                    return RedirectToAction("AddDepartment");
                }
            }
            return View();
        }

        // GET: UCRMS/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Department department = db.Departments.Find(id);
            if (department == null)
            {
                return HttpNotFound();
            }
            return View(department);
        }

        // POST: UCRMS/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Code,Name")] Department department)
        {
            if (ModelState.IsValid)
            {
                db.Entry(department).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(department);
        }

        // GET: UCRMS/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Department department = db.Departments.Find(id);
            if (department == null)
            {
                return HttpNotFound();
            }
            return View(department);
        }

        // POST: UCRMS/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Department department = db.Departments.Find(id);
            db.Departments.Remove(department);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        #endregion
        
        #region Course Settings

        
        // GET: UCRMS
        public async Task<ActionResult> IndexCourse()
        {
            VM_Course vmCourse = new VM_Course();
            await Task.Run(() => vmCourse.GetCourseList());
            return View(vmCourse);
        }

        // GET: UCRMS/Details/5
        public ActionResult CourseDetails(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            VM_Course course = new VM_Course();
            
            if (course.GetCourse(id) == null)
            {
                return HttpNotFound();
            }
            
            return View(course.GetCourse(id.Value));
        }

        // GET: UCRMS/Create
        public ActionResult CreateCourse()
        {
            ViewBag.Dept = new SelectList(db.Departments.ToList().OrderBy(s=>s.Id),"Id","Name");
            ViewBag.Semesters = new SelectList(db.Semesters.ToList().OrderBy(s=>s.Id),"Id","Name");
             return View();
        }

        // POST: UCRMS/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateCourse(Course course)
        {
            if (ModelState.IsValid)
            {
                ViewBag.Dept = new SelectList(db.Departments.ToList().OrderBy(s=>s.Id),"Id","Name");
                ViewBag.Semesters = new SelectList(db.Semesters.ToList().OrderBy(s=>s.Id),"Id","Name");
                if (!db.Courses.Any(n => n.Code == course.Code && n.Name == course.Name))
                {
                    db.Courses.Add(course);
                    db.SaveChanges();
                    return RedirectToAction("IndexCourse");
                }
                else
                {
                    return RedirectToAction("CreateCourse");
                }
                
            }
            return View();
        }

        // GET: UCRMS/Edit/5
        public ActionResult EditCourse(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course Course = db.Courses.Find(id);
            if (Course == null)
            {
                return HttpNotFound();
            }
            ViewBag.Dept = new SelectList(db.Departments.ToList().OrderBy(s=>s.Id),"Id","Name");
            ViewBag.Semesters = new SelectList(db.Semesters.ToList().OrderBy(s=>s.Id),"Id","Name");
            return View(Course);
        }

        // POST: UCRMS/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditCourse(Course Course)
        {
            if (ModelState.IsValid)
            {
                ViewBag.Dept = new SelectList(db.Departments.ToList().OrderBy(s=>s.Id),"Id","Name");
                ViewBag.Semesters = new SelectList(db.Semesters.ToList().OrderBy(s=>s.Id),"Id","Name");
                db.Entry(Course).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("IndexCourse");
            }
            return View(Course);
        }

        // GET: UCRMS/Delete/5
        public ActionResult DeleteCourse(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = db.Courses.Find(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            return View(course);
        }

        // POST: UCRMS/Delete/5
        [HttpPost, ActionName("DeleteCourse")]
        [ValidateAntiForgeryToken]
        public ActionResult CourseDeleteConfirmed(int id)
        {
            Course course = db.Courses.Find(id);
            db.Courses.Remove(course);
            db.SaveChanges();
            return RedirectToAction("IndexCourse");
        }
        
        #endregion

        #region Teacher Settings

        /// <summary>
        /// Teacher List View------
        /// </summary>
        /// <returns></returns>
        public async Task<ActionResult> IndexTeacher()
        {
            try
            {
                VM_Teacher vmTeacher = new VM_Teacher();
                await Task.Run(() => vmTeacher.GetTeacherList());
                return View(vmTeacher);
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                throw;
            }
        }

        /// <summary>
        /// Load Form for Teacher Entry
        /// </summary>
        /// <returns></returns>
        public ActionResult AddTeacherInfo()
        {
            try
            {
                ViewBag.Department = new SelectList(d.GetDeptList(), "Value", "Text");
                ViewBag.Designation = new SelectList(d.GetDesignationList(), "Value", "Text");
                return View();
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                throw;
            }
        }

        /// <summary>
        /// Submit form for Teacher Infomation
        /// </summary>
        /// <param name="vmTeacher"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]

UCMRS/UCMRS/Views/UCRMS/AddDepartment.cshtml
@model UCMRS.Models.Entity.Department

@{
    ViewBag.Title = "Create";
}

@using (Html.BeginForm("AddDepartment", "UCRMS",FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="card text-center">
        <h3 class="card-header">Add Department</h3>
        <div class="card-body">
            <div class="row ">
                <div class="col-md-5">
                    <div class="form-group">
                        <div class="col-md-3">
                            @Html.LabelFor(model => model.Code, htmlAttributes: new {@class = "col-form-label text-left" })
                        </div>
                        <div class="col-md-7">
                            @Html.EditorFor(model => model.Code, new {htmlAttributes = new {@class = "form-control"}})
                            @Html.ValidationMessageFor(model => model.Code, "", new {@class = "text-danger"})
                        </div>
                    </div>
                </div>
                <div class="col-md-5">
                    <div class="form-group">
                        <div class="col-md-3">
                            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "col-form-label text-left" })
                        </div>
                        <div class="col-md-7">
                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="form-group">
                        <button class="btn btn-primary btn-sm">Add &nbsp;<i class="fa fa-plus-circle"></i></button>
                    </div>
                </div>
            </div>
        </div>
    </div>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

UCMRS/UCMRS/Views/UCRMS/AddEnrollCourse.cshtml
@model UCMRS.Models.Entity.EnrollCourse

@{
    ViewBag.Title = "AddEnrollCourse";
}


@using (Html.BeginForm("AddEnrollCourse","UCRMS",FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="card text-center">
        <h3 class="card-header ">Enroll Course</h3>
        <hr />
        <div class="card-body">
            <div class="row form-group">
                <div class="col-md-6">
                    @Html.LabelFor(model => model.StudentId, htmlAttributes: new { @class = "control-label col-md-4 text-left" })
                    <div class="col-md-8 input-group">
                        @Html.DropDownListFor(model => model.StudentId, ViewBag.Student as IEnumerable<SelectListItem>,
                       "Select Reg No", new { @class = "form-control"})
                        <span class="input-group-addon"><span class="glyphicon glyphicon-user"></span></span>
                        @Html.ValidationMessageFor(model => model.StudentId, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-md-6">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-4 text-left" })
                    <div class="col-md-8 input-group">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                        <span class="input-group-addon"><span class="glyphicon glyphicon-user"></span></span>
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="row form-group">
                <div class="col-md-6">
                    @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-4 text-left" })
                    <div class="col-md-8 input-group">
                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                        <span class="input-group-addon"><span class="glyphicon glyphicon-envelope"></span></span>
                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-md-6">
                    @Html.LabelFor(model => model.Department, htmlAttributes: new { @class = "control-label col-md-4 text-left" })
                    <div class="col-md-8 input-group">
                        @Html.EditorFor(model => model.Department, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                        <span class="input-group-addon"><span class="glyphicon glyphicon-briefcase"></span></span>
                        @Html.ValidationMessageFor(model => model.Department, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="row form-group">
                <div class="col-md-6">
                    @Html.LabelFor(model => model.CourseId, htmlAttributes: new { @class = "control-label col-md-4 text-left" })
                    <div class="col-md-8 input-group">
                        @Html.DropDownListFor(model => model.CourseId, ViewBag.Course as IEnumerable<SelectListItem>,
                            "Select Course",new { @class = "form-control"})
                        <span class="input-group-addon"><span class="glyphicon glyphicon-book"></span></span>
                        @Html.ValidationMessageFor(model => model.CourseId, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-md-6">
                    @Html.LabelFor(model => model.Date, htmlAttributes: new {@class = "control-label col-md-4 text-left" })
                    <div class="col-md-8 input-group">
                        @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                        <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
                       
                    </div>
                    @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="row form-group">
                <div class="col-md-6"></div>
                <div class="col-md-6 input-group">
                    <button class="btn btn-primary pull-right">Enroll&nbsp;<i class="fa fa-plus-circle"></i></button>
                </div>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        $(document).ready(function() {
            $("#StudentId").change(function() {
                $.ajax({
                    type: "POST",
                    url: "@Url.Action("RegDropDown","Helper")",
                    datatype: "Json",
                    data: { id: $("#StudentId").val() },
                    success: function(data) {
                        Name = $("#Name").val(data.Name);
                        Email = $("#Email").val(data.Email);
                        DName = $("#Department").val(data.DeptName);
                        // $("#RemainingCredit").text(data.RemainingCredit) ;

                    }
                });
            });
        });
    </script>
}

UCMRS/UCMRS/Views/UCRMS/Delete.cshtml
@model UCMRS.Models.Entity.Department

@{
    ViewBag.Title = "Delete";
}

<div class="card text-center">
    <h3 class="card-header">Delete Department</h3>
    <div class="card-body">
        <h3>Are you sure you want to delete this?</h3>
        <div>
            <h4>Department</h4>
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Code)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Code)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Name)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Name)
                </dd>

            </dl>

            @using (Html.BeginForm("Delete","UCRMS"))
            {
                @Html.AntiForgeryToken()

                <div class="form-actions no-color">
                    <input type="submit" value="Delete" class="btn btn-default" /> |
                    @Html.ActionLink("Back to List", "Index")
                </div>
            }
        </div>
    </div>
</div>

UCMRS/UCMRS/Views/UCRMS/EditStudent.cshtml
@model UCMRS.Models.Entity.Student

@{
    ViewBag.Title = "EditStudent";
}

@using (Html.BeginForm("EditStudent", "UCRMS", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="card text-center">
        <h3 class="card-header">Add Student</h3>
        <div class="card-body">
            <div class="row form-group">
                <div class="col-md-6">
                    <div class="col-md-5">
                        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "col-form-label text-left" })
                    </div>
                    <div class="col-md-7">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="col-md-5">
                        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "col-form-label text-left" })
                    </div>
                    <div class="col-md-7">
                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="row form-group">
                <div class="col-md-6">
                    <div class="col-md-5">
                        @Html.LabelFor(model => model.ContactNo, htmlAttributes: new { @class = "col-form-label text-left" })
                    </div>
                    <div class="col-md-7">
                        @Html.EditorFor(model => model.ContactNo, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ContactNo, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="col-md-5">
                        @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "col-form-label text-left" })
                    </div>
                    <div class="col-md-7">
                        @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="row form-group">
                <div class="col-md-6">
                    <div class="col-md-5">
                        @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "col-form-label text-left" })
                    </div>
                    <div class="col-md-7">
                        @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-md-6">
                    <div class=" col-md-5">
                        @Html.LabelFor(model => model.DeptId, htmlAttributes: new { @class = "col-form-label text-left" })
                    </div>
                    <div class=" col-md-7">
                        @Html.DropDownListFor(model => model.DeptId, ViewBag.Department as IEnumerable<SelectListItem>,
                            "Select Department", new { @class = "form-control"})
                        @Html.ValidationMessageFor(model => model.DeptId, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="row form-group">
                <div class="col-md-6">
                    <div class="col-md-5">
                        @Html.LabelFor(model => model.RegNo, htmlAttributes: new { @class = "col-form-label text-left" })
                    </div>
                    <div class="col-md-7">
                        @Html.EditorFor(model => model.RegNo, new { htmlAttributes = new { @class = "form-control", @readonly= "readonly" } })
                        @Html.ValidationMessageFor(model => model.RegNo, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="row form-group">
                <div class="col-md-6"></div>
                <div class="col-md-6 ">
                    <button class="btn btn-primary pull-right">Save &nbsp;<i class="fa fa-plus-circle"></i></button>
                </div>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        $(document).ready(function(){
            $("#DeptId").change(function () {

                $.ajax({
                    type: "POST",
                    url: '@Url.Action("GenerateRegNo", "Helper")',
                    datatype: "Json",
                    data: { id: $("#DeptId").val() },
                    success: function (data) {
                        $('#RegNo').val(data);
                    }
                });
            });

        });
        
        
    </script>
    
}

UCMRS/UCMRS/Views/UCRMS/IndexCourseStat.cshtml
@model UCMRS.Models.Entity.Department

@{
    ViewBag.Title = "IndexCourseStat";
}
<div class="card">
    <div class="card-header">View Course Statistics</div>
    <div class="card-body">

        @using (Html.BeginForm("IndexCourseStat", "UCRMS", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="card">
                <h4 class="card-header">Course Statistics</h4>
                <div class="card-body">
                    <div class="row">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Id, htmlAttributes: new {@class = "control-label col-md-4 text-left"})
                            <div class="col-md-6">
                                @Html.DropDownListFor(model => model.Id, ViewBag.Dept as IEnumerable<SelectListItem>,
                                    "Select Department", new {@class = "form-control"})
                                @Html.ValidationMessageFor(model => model.Id, "", new {@class = "text-danger"})
                            </div>
                        </div>
                    </div>
                    <hr/>
                    <div class="row" id="tableDiv">
                        <div class="card text-center">
                            <h4 class="card-header"> Course Information</h4>
                            <div class="card-body">
                                <div class="">
                                    <table class="table table-striped table-bordered" id="courseStatTable">
                                        <thead>
                                        <tr>
                                            <td class="font-weight-bold">Code</td>
                                            <td class="font-weight-bold">Name/Title</td>
                                            <td class="font-weight-bold">Semester</td>
                                            <td class="font-weight-bold">Assigned To</td>
                                        </tr>
                                        </thead>
                                        <tbody></tbody>
                                        <tfoot></tfoot>
                                    </table>
                                </div>
                            
                            </div>
                        </div>
                    </div>
                    
                </div>
            </div>
        }


    </div>
</div>

@section Scripts{
    
    <script>
        $(document).ready(function() {
            $("#courseStatTable").hide();
            $("#tableDiv").hide();
           $('#Id').on("change", function (e) {

               $("#courseStatTable").show();
               $("#tableDiv").show();
               $("#courseStatTable tbody").empty();
            $.ajax({
                    type: "POST",
                    url: "@Url.Action("CourseStat","Helper")",
                datatype: "Json",
                data: { id: $("#Id").val() },
                success: function(data) {
                    $.each(data,function(index, value) {

                        $("#courseStatTable tbody").append("<tr>" +
                            "<td>" + data[index].code + "</td >" + 
                            "<td>" + data[index].name + "</td >" +
                            "<td>" + data[index].sem + "</td >" +
                            "<td>" + data[index].assignTo +"</td >" +
                            "</tr>");
                    });
                },

                error: function() {
                    alert("No Data Found");
                }
            });
        });
        
    });
    </script>
}